### ISSUE TITLE
Problem running backend

### ISSUE THREAD

**Issue by TWry** [PacktPublishing/Modern-Web-Development-with-the-FARM-Stack#1]
I'm getting an `ImportError: cannot import name 'FastAPICache' from 'fastapi_cache'` when trying to run the backend. I had to manually install the aioredis and fastapi_cache dependencies. Any ideas, please?

**Comment by freethrow** [comment]
Yes, they are dependencies indeed. I will update the requirements file.

**Comment by TWry** [comment]
Thanks, however, the ImportError does not go away. Sorry, I should have stated that in my initial posting. Maybe it's a wrong version that is being installed?

**Comment by freethrow** [comment]
I ll get back to you this evening and try to figure it out. Ok?

**Comment by freethrow** [comment]
Can you just tell me what type of system you are running? Windows, Linux?

**Comment by TWry** [comment]
Sure: macOS 12.6 and Python 3.10.7 in a virtual env created with `python3 -m venv`.

**Comment by freethrow** [comment]
Excuse me, did you install https://github.com/long2ice/fastapi-cache? It is called fastapi-cache2 with the 2. I have checked and I used:
`pip install fastapi-cache2 aioredis`
but maybe you should add 
`pip install "fastapi-cache2[redis]"`

Please let me know if this solves the issue. I haven't been able to develop on a Mac, I only tested on Windows (11) and the latest Ubuntu.

**Comment by TWry** [comment]
This seems to do the trick, thanks!

**Comment by freethrow** [comment]
Great, glad I could help!
