### ISSUE TITLE
Errors in frontend

### ISSUE THREAD

**Issue by TWry** [PacktPublishing/Modern-Web-Development-with-the-FARM-Stack#2]
I'm not sure if this is intentional - there are car items in the chapter 2 CSV file that are not compatible with the backend pydantic model attributes. Namely, the cm3 attribute has values that are less than 400 (I think I counted 74), and 11 that are greater than 8000. This was not caught and led to `failed to load` errors being displayed.

I also had issues installing the dependencies in chapter 9 and had to force the installation (i.e. `npm install --force`) because of a dependency conflict with `@react-pdf/renderer`. It conflicted with the react dependency in the base package. 

Also, there was one more dependency missing in the requirements.txt in the backend: `joblib`.

**Comment by freethrow** [comment]
@TWry  Sorry I got to see this only today. Let's see. 

The first issue - the CSV file in Chapter 2 contains many unfiltered cars, so you should point me to the exact part in the book in which you see the error pop out.

The second part - you are absolutely right: there shouldn't be a react renderer dependency. To be honest, I was thinking of including it in the book and in the code, btu at the end I discarded the idea. I will update the package.json file accordingly. Anyway, if you install the code following the book, there shouldn't be problems.

As far as the third issue is concerned, yes - joblib is necessary for loading the machine learning model and it should be in the requirements - I will fix it as soon as possible.

**Comment by freethrow** [comment]
Fixed.
