### ISSUE TITLE
Chapter5: Building the backend for Our application

### ISSUE THREAD

**Issue by yawtalkstechs** [PacktPublishing/Modern-Web-Development-with-the-FARM-Stack#3]
- When I try to run the main.py using this command: python main.py
I get an error -:
NameError: name 'uvicorn' is not defined

**Comment by freethrow** [comment]
Ah, I believe an import of uvicorn is missing at the top. Should be fixed now.

**Comment by yawtalkstechs** [comment]
> Ah, I believe an import of uvicorn is missing at the top. Should be fixed now.

After, importing  uvicorn 
The code is now running.
Thank you
