### ISSUE TITLE
axios request leads to an error. The api-route-call is not logged. Its not possible to create a new car

### ISSUE THREAD

**Issue by hjkrannig** [PacktPublishing/Modern-Web-Development-with-the-FARM-Stack#5]
Hi Marko, hi everybody, when navigating the given Links we installed in V.8 (Chapter8) everything works fine. The user seems to be known in all components using useAuth().
But trying to send the full-filled form to create a new car, I only see the listed error-stack. It seems that axios is missing something. I tried even with the exact example-code ...it does not work!
Can anybody help?
[error-stack.txt](https://github.com/PacktPublishing/Full-Stack-FastAPI-React-and-MongoDB/files/10077266/error-stack.txt)

**Comment by freethrow** [comment]
I am looking at it, I'll let you know as soon as I figure it out!
Marko

**Comment by freethrow** [comment]
Did you by any chance JSON.stringify() the form data before passing it to axios?

The chunk of code that works for me on my machine, as well as on Vercel is the following:

`const handleSubmit = async (e) => {
    e.preventDefault();

    const formData = new FormData();

    formData.append("brand", brand);
    formData.append("make", make);
    formData.append("year", year);
    formData.append("km", km);
    formData.append("cm3", cm3);
    formData.append("price", price);
    formData.append("picture", picture);

    setLoading(true);

    try {
      const response = await axios({
        method: "POST",
        url: `${process.env.NEXT_PUBLIC_API_URL}/cars/`,
        data: formData,

        headers: {
          "Content-Type": "multipart/form-data",
          Authorization: `bearer ${jwt}`,
        },
      });
    } catch (error) {
      console.log("ERROR:", error);
    }`
