### ISSUE TITLE
Chapter3 - Code and example mismatches

### ISSUE THREAD

**Issue by BernardoEstevao** [PacktPublishing/Modern-Web-Development-with-the-FARM-Stack#7]
Hi Marko. Sorry if I should open one issue per each of the issues I'm outlining here. They're all in the same part of the book, that's why I wrote all in one.

In chapter 3 when you start writing about the body (`The request body - the bulk of the data`), you start by showing a snippet for a `"/cars"` endpoint without any validation or modeling, just to explain how the mechanism works. No issues here.

Then you propose to enforce a certain structure (of a car) and explain that we need a Pydantic model with the desired types (which would be brand, model and production year), followed by an example that should be in the file [chapter3_body2.py](https://github.com/PacktPublishing/Full-Stack-FastAPI-React-and-MongoDB/blob/main/chapter3/chapter3_body2.py).
The code you show in the book is as follows:
```
from fastapi import FastAPI, Body
from pydantic import BaseModel
class InsertCar(BaseModel):
    brand: str
    model: str
    year: int
app = FastAPI()
@app.post("/cars")
async def new_car(data: Dict=Body(...)):
    print(data)
    return {
        "message" : data
    }
```
(at this point the code you write is different from the file in the repo, but later on in the book this code gets updated to what we have in the repo)

After this code you explain that now the fields will go through Pydantic parsing and validation, throwing error messages if something doesn't conform to the data specifications. You even show an example of a call with:
```
(venv) λ http POST "https//localhost:8000/carsmodel" brand="Fiat" model="500" breed="Dobermann" year=2018
HTTP/1.1 200 OK
{
    "message": {
        "brand": "Fiat",
        "model": "500",
        "year": 2018
    }
}
```

The issues I found here are:

1. In the example you call `/carsmodel` while in the code we only define `"/cars"`
2. We're missing an `from typing import Dict`
3. In the example code we're not actually validating that the Body matches the specifications, so the result of the call would include the `breed="Dobermann"` as well. If we keep reading and update the code to have the `user` (as shown in the file in the repo) then yes, the validation takes place.

Please correct me if I'm wrong or if I missed something, but at that point in the book I would expect the code above to validate the data we send in the POST.
This is by no means negative criticism, I'm loving the book so far!

**Comment by freethrow** [comment]
Hello Bernardo and thank you for reaching out and for your kind words. Yes, there was a bit of a mix-up in the code and the text that you are citing and I have tried to address it. The code in the repo should be updated, but here I cannot add much about the errata in the book. I will however try to address the issues that you mentioned here, in a comment:

1. Yes, it should be "/cars"
2. We are missing the import from typing
3. Yes - when there is no Pydantic model, there is no validation - everything flows through the request.

For completeness, I am [attaching in a Gist](https://gist.github.com/freethrow/d97b3cbdcad77dcdb8c9042c849eba16)
 part of an email that I sent a month ago to a person that had (rightfully so) trouble going through that part of the code.

I am really sorry, but even after multiple reviews this part remained "uncovered". Should you find other inconsistencies or errors, please do not hesitate to contact me through GitHub or directly
Kind regards
Marko

**Comment by BernardoEstevao** [comment]
Hi Marko, thanks for the update!
Just wanted to be sure you were aware of this and maybe save someone else some questions in the future.
